name: Build & Validate

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: npm ci
      - run: make code
      - run: make commit.lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: npm ci
      - run: make test

  build:
    name: Build
    runs-on: ubuntu-latest

    needs:
      - linting
      - tests

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: npm ci
      - run: make build
      - run: make publish.dry
