name: Project

on:
  push:
    branches:
      - main
      - next

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: node -v
      - run: npm -v

      - uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci --ignore-scripts

      - run: make code
      - run: make test
      - run: make build
      - run: make package
